### ISSUE TITLE
JSON Path spec

### ISSUE THREAD

**Issue by gregsdennis** [danielaparker/JsonCons.Net#5]
Please be involved with the JSON Path spec effort: https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base.  We need more opinions.

**Comment by danielaparker** [comment]
I don't think so. I don't think I was very effective when I was participating. I could spend several hours preparing what I thought was a well presented post, and it often seemed that you were the only one that read it. And I didn't enjoy my interactions with Carston. 

Best regards,
Daniel





On Tuesday, August 10, 2021, 02:59:39 p.m. EDT, Greg Dennis ***@***.***> wrote: 







—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by danielaparker** [comment]
Ah, I replied from my inbox, and hadn't realized this had been sent to the project issues! I'll delete this response from the issues, and edit the other.

Best regards,
Daniel 






On Tuesday, August 10, 2021, 04:34:50 p.m. EDT, Daniel Parker ***@***.***> wrote: 





I don't think so. I don't think I was very effective when I was participating. I could spend several hours preparing what I thought was a well presented post, and it often seemed that you were the only one that read it. And I didn't enjoy my interactions with Carston. 

Best regards,
Daniel





On Tuesday, August 10, 2021, 02:59:39 p.m. EDT, Greg Dennis ***@***.***> wrote: 







—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
