### ISSUE TITLE
Error in readme

### ISSUE THREAD

**Issue by gregsdennis** [danielaparker/JsonCons.Net#6]
> The specification of JSONPath filter expressions is greatly influenced by James Saryerwinnie's JMESPath

I think the influence is the other way.  JSON Path came first.  JMESPath expands on it.

**Comment by danielaparker** [comment]
Hi Greg,

It's a pleasure to here from you.

Regarding your point, I meant on the specification of my own JsonCons JsonPath filter expressions, in the C++ and now .Net implementations. That should have been more clearly expressed, thanks. I wouldn't presume to make statements about JSONPath, only my hyphenated version of it. I'll update that text.

It took me six months to implement in C++ the JMESPath specification. It left an indelible impression on me, I felt like I was in the presence of an absolutely first class mind in James Saryerwinnie.  If a specification can be beautiful, the JMESPath specification is beautiful. I mean that independently of JMESPath syntax, which not everyone might care for. But the specification itself is just so clear and well thought out. I find myself borrowing copiously from it when trying to do something with JSONPath filter expressions, and felt the need to acknowledge that debt.   

Best regards,
Daniel






On Tuesday, August 10, 2021, 03:02:57 p.m. EDT, Greg Dennis ***@***.***> wrote: 







>  
> The specification of JSONPath filter expressions is greatly influenced by James Saryerwinnie's JMESPath
> 

I think the influence is the other way. JSON Path came first. JMESPath expands on it.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
